In [1]:
import torch
from torch import nn
from torch_geometric.data import DataLoader
import numpy as np
import sys
sys.path.insert(0,'..')
sys.path.insert(0,'../..')
from dig.threedgraph.dataset import QM7, QM, QM9
from dig.threedgraph.method import SphereNet, SchNet, DimeNetPP
import matplotlib.pyplot as plt

from rdkit import RDLogger
RDLogger.DisableLog('rdApp.*')

from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [3]:
dataset = QM(root='dataset/', name='qm8')
print(dataset.data)
print(dataset.data.smiles[-2:])
print(dataset.data.pos[-10:])
print(dataset.data.minpos_mmff[-10:])

Data(pos=[331551, 3], max1pos_uff=[331551, 3], max2pos_uff=[331551, 3], minpos_mmff=[331551, 3], max1pos_mmff=[331551, 3], max2pos_mmff=[331551, 3], z=[331551], smiles=[20620], E1_CC2=[20620], E2_CC2=[20620], f1_CC2=[20620], f2_CC2=[20620], E1_PBE0=[20620], E2_PBE0=[20620], f1_PBE0=[20620], f2_PBE0=[20620], E1_CAM=[20620], E2_CAM=[20620], f1_CAM=[20620], f2_CAM=[20620])
['[H]C1([H])OC([H])(C(F)(F)F)C1([H])[H]', '[H]C1([H])OC([H])([H])C1([H])C(F)(F)F']
tensor([[ 0.0705, -0.0922,  0.5059],
        [ 1.4473, -0.2117, -0.1656],
        [ 2.3108,  0.7100,  0.3971],
        [ 1.9502, -1.4818,  0.0478],
        [ 1.3716,  0.0182, -1.5300],
        [-0.7361, -1.3762, -1.1174],
        [-1.6551, -1.4489,  0.4932],
        [-1.1416,  1.6724,  0.9906],
        [-0.2123,  1.8076, -0.6100],
        [ 0.0834, -0.2694,  1.6040]])
tensor([[ 0.0686,  0.1227, -0.4919],
        [ 1.4466,  0.0907,  0.0726],
        [ 1.4530, -0.2229,  1.3865],
        [ 2.1991, -0.8240, -0.5790],
        [ 2.0406,  1.2964

In [ ]:
from rdkit import Chem
from rdkit.Chem import AllChem

s = 'CCOCCC(F)(F)F'
mol = Chem.MolFromSmiles(s)
mol = Chem.AddHs(mol)
AllChem.EmbedMolecule(mol)
p = list(mol.GetConformer().GetAtomPosition(17))
print(p)

In [ ]:
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Geometry import Point3D

s = 'COCCCC(F)(F)F'
mol = Chem.MolFromSmiles(s)
mol = Chem.AddHs(mol)
AllChem.EmbedMolecule(mol, useRandomCoords=False) # AllChem.ETKDG(), randomSeed=2222, useRandomCoords=True 
conf = mol.GetConformer()
arr = AllChem.MMFFOptimizeMoleculeConfs(mol, maxIters=2000)
e = [v  for s, v in arr]
sortidx = np.argsort(e)
minidx = int(sortidx[0])
#maxidx1, maxidx2 = int(sortidx[-1]), int(sortidx[-2])
minpos = mol.GetConformer(minidx).GetPositions()
#max1pos = mol.GetConformer(maxidx1).GetPositions()
#max2pos = mol.GetConformer(maxidx2).GetPositions()
print(minpos)
#print(list(conf.GetAtomPosition(0)))
#print(list(conf.GetAtomPosition(1)))
#print(list(conf.GetAtomPosition(16)))
#print(list(conf.GetAtomPosition(17)))
#print(list(conf.GetAtomPosition(-1)))
mol

In [ ]:

s = 'COCCCC(F)(F)F'
mol = Chem.MolFromSmiles(s)
mol = Chem.AddHs(mol)
conf = mol.GetConformer()

# in principal, you should check that the atoms match
for i in range(m.GetNumAtoms()):
    x,y,z = xyz_coordinates[i]
    conf.SetAtomPosition(i,Point3D(x,y,z))

In [ ]:
dataset = QM(root='dataset/', name='qm7')
dataset.data
a = [111, 0.35862867,0.35862867,0,0,0.25632133,0.2684693,0,0,0.25632133,0.2684693,0,0,0.24487913,0.25505134,0,0]
b = slice(1, 17)
print(a[b])
print(len(a))

In [ ]:
dataset = QM(root='dataset/', name='qm8')
dataset.data

In [ ]:
from rdkit import Chem
from rdkit.Chem import AllChem

s = '[H]C([H])([H])C([H])([H])C#N'
s = 'C([H])([H])([H])[H]'
mol = Chem.MolFromSmiles(s)
mol = Chem.AddHs(mol)
AllChem.EmbedMolecule(mol , randomSeed=2222, useRandomCoords=True)
conf = mol.GetConformer()
print(list(conf.GetAtomPosition(0)))
print(list(conf.GetAtomPosition(1)))
mol

In [ ]:
AllChem.EmbedMultipleConfs(mol, numConfs=3, randomSeed=2222, numThreads=0)
rmslist = []
AllChem.AlignMolConformers(mol, RMSlist=rmslist)
#print(mol)
#print(smiles)
print(rmslist)
rangeidx = len(rmslist)+1
sortidx = [i for i in range(rangeidx)]
minidx = sortidx[0]
maxidx1, maxidx2 = sortidx[-1], sortidx[-2]   

minpos = mol.GetConformer(minidx).GetPositions()
max1pos = mol.GetConformer(maxidx1).GetPositions()
max2pos = mol.GetConformer(maxidx2).GetPositions()

minpos_etkdg = torch.tensor(minpos, dtype=torch.float)
max1pos_etkdg = torch.tensor(max1pos, dtype=torch.float)
max2pos_etkdg = torch.tensor(max2pos, dtype=torch.float)
print(minpos_etkdg)
print(max1pos_etkdg)
print(max2pos_etkdg)
mol

In [ ]:
s = 'C([H])([H])([H])[H]'
mol = Chem.MolFromSmiles(s)
mol = Chem.AddHs(mol)
mol

In [ ]:
#tensor([[ 9.7780e-01, -2.5000e-03, -4.4000e-03],
        [ 2.0953e+00, -2.4000e-03,  4.1000e-03],
        [ 3.7268e+00,  1.0269e+00,  4.1000e-03],
        [ 1.6782e+00, -5.2770e-01,  8.7810e-01],
        [-3.5973e+00, -5.0750e-01, -9.0540e-01]])